### ISSUE TITLE
Adding base library to document throws Exception

### ISSUE THREAD

**Issue by MenschMitHut** [AutomationML/AMLEngine2.1#3]
Hi,

adding the base library to a document throws an exception

```
AutomationMLInterfaceClassLibType.InterfaceClassLib(caexDocument);
->
Aml.Engine.CAEX.SchemaConformanceException: 'The current document and the imported library use different CAEX Versions; To do a schema transformation the service needs to be registered'
```

To reproduce this bug, build and run example 3 from the frontpage.

**Comment by jprinz** [comment]
The exception is raised, because the Base libraries for AutomationML 2.1 are not yet released to the public and the access is restricted. If a Version 2.15 document is created instead, the base libraries will be included. I will update the example on the Front page accordingly.

**Comment by jprinz** [comment]
As long as the AutomationML 2.1 base libraries are not finally released, the version 2.0 libraries are added. The Fix is contained in Version 1.0.16 of Aml.Engine.

**Comment by MenschMitHut** [comment]
Thanks,

but the fix only works in the .net4.7 assemblie. The .net4.6 throws:
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Der Wert darf nicht NULL sein.
Parametername: inStream
  Source=AML.Engine
  StackTrace:
   at Aml.Engine.CAEX.CAEXDocument.LoadFromStream(Stream inStream)
   at Aml.Engine.AmlObjects.AMLLibraryType`1.LoadExternalLibrary(CAEXDocument document, String resourceName, Func`2 ImportLibrary)
   at Aml.Engine.AmlObjects.AutomationMLInterfaceClassLibType.InterfaceClassLib(CAEXDocument document)
   at TestApp.Program.Main(String[] args) in ...\visual studio 2017\Projects\TestApp\Program.cs:line 20
```

**Comment by jprinz** [comment]
fixed in v1.0.18

**Comment by MenschMitHut** [comment]
I still get the same error with the .net46 assembly

```
var caexDocument = CAEXDocument.New_CAEXDocument();
// exception thrown here
AutomationMLInterfaceClassLibType.InterfaceClassLib(caexDocument);
```

With CAEX version 2.15 everything works fine.

**Comment by jprinz** [comment]
sorry for that, I missed to change a compile setting for the .NET 4.6 assembly. I'll correct it with the next update.

**Comment by MenschMitHut** [comment]
No problem ;)
Thanks for the fix and fast response!
